apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: test 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app
        image: ashish13997/web-app:v1
        ports:
        - containerPort: 80
